export {Profile} from './profile/profile'
export {Login} from './login/login'
export {Registration} from './registration/registration'
export {Tasks} from './tasks-page/tasks'
export {NotFoundPage} from './not-found-page/not-found-page'